# Generated by Django 5.1.2 on 2024-11-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conso',
            fields=[
                ('dateC', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('numE', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('idMat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qcm',
            fields=[
                ('dateQ', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('numSem', models.IntegerField()),
            ],
            options={
                'unique_together': {('annee', 'numSem')},
            },
        ),
        migrations.CreateModel(
            name='CorrespondConso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='home.conso')),
                ('matiere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conso_unique', to='home.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Participe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conso')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='EstNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.etudiant')),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondQcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_unique', to='home.matiere')),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='home.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='RepondreBilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('demande', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bilan')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.etudiant')),
            ],
        ),
    ]
