# Generated by Django 5.1.2 on 2025-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participe',
            name='estAbsent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
