# Generated by Django 5.1.2 on 2025-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_participe_estabsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participe',
            name='estAbsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='bilan',
            index=models.Index(fields=['dateB'], name='home_bilan_dateB_ceeb96_idx'),
        ),
        migrations.AddIndex(
            model_name='conso',
            index=models.Index(fields=['dateC'], name='home_conso_dateC_de1ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='estnote',
            index=models.Index(fields=['etudiant'], name='home_estnot_etudian_7ed5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['numE'], name='home_etudia_numE_e9f1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['nomMat'], name='home_matier_nomMat_7f0402_idx'),
        ),
        migrations.AddIndex(
            model_name='participe',
            index=models.Index(fields=['etudiant', 'conso'], name='home_partic_etudian_384f91_idx'),
        ),
        migrations.AddIndex(
            model_name='qcm',
            index=models.Index(fields=['dateQ'], name='home_qcm_dateQ_3d5904_idx'),
        ),
        migrations.AddIndex(
            model_name='repondrebilan',
            index=models.Index(fields=['etudiant', 'bilan'], name='home_repond_etudian_9f40f2_idx'),
        ),
    ]
